### ISSUE TITLE
[TRACKING] Importer/Exporter to-do

### ISSUE THREAD

**Issue by pepperoni505** [flybywiresim/glTF-Blender-IO-MSFS#1]
This is a to-do list of things left to do (things will get added/changed as time goes on)

* [ ] Importer
  * [ ] Model
  * [ ] Materials
    * [x] Some materials import incorrectly
  * [ ] Animations

* [ ] Exporter
  * [ ] Model
    * [x] Armature
      * [x] Fix weird bone thing that causes sharklets to flip
    * [ ] Triangulate at export 
    * [ ] Slats are deformed (possibly armature related)
    * [ ] Not all nodes are exported (cockpit rudder pedals)
    * [ ] Fix x0_ nodes exporting when they shouldn't?
    * [ ] CJ4 ground models deformed
    * [ ] For some planes, the model looks flat shaded
    * [ ] Some meshes have weird scaling
    * [ ] Maybe support models that aren't built?
    * [ ] Normal smoothness (check no grab on engine)
    * [ ] Smoothness of mesh (hublots for example)
    * [ ] Normal view in blender (investigate for any issues)
    * [ ] C172 wheel
  * [ ] Materials
    * [x] Fix flaps decal issue - could be related to rounding the position of nodes
    * [x] Some materials are too metallic
    * [ ] Export materials as .DDS
    * [ ] Generate JSON for materials
    * [ ] Dont export `pbrMetallicRoughness` if the material is blank (for example glTFValidator_Added_Default_Material)
    * [ ] Livery exporter? Exports with livery ready to go
    * [ ] Double material export on exterior (`{ "extensions": { "MSFT_texture_dds": { "source": 3 } } },`)
    * [x] Decals under tail messed up
    * [x] Fix workaround in Material class function to_dict that prevents an error
    * [ ] Rewrite MSFSToolkit addition?
    * [x] Fix albedo issues on Caravan
    * [x] Fix `NameError: name 'switch_msfs_blendmode' is not defined`
    * [x] Fix Material Type rearranging when changing type - seems to be fixed
    * [ ] Add game option for screen/display
    * [x] Fix caravan interior issues (out of range error)
    * [x] Optimize texture import
    * [ ] Auto-locate MSFS install directory?
    * [ ] Handle `None` image at export
    * [x] 747 import issues (texture doesn't exist)
    * [ ] X-Cub floor issues
    * [ ] Clean up code for blend mask
    * [ ] Alpha mode to masked for blend masks?
    * [ ] Support images that aren't DDS
    * [ ] Should always export as DDS?
    * [ ] Issue when importing two models that have materials that share a name
    * [ ] Alpha multiplier issues (possibly causing X-Cub floor problems?)
    * [ ] Delete material extension files?
    * [ ] Optimize the alpha channel check
    * [ ] OpenGL normal map?
    * [ ] Some variables declared as None when they shouldn't be?
    * [ ] Don't load material data if material is already made
    * [ ] A320 Cockpit overhead light doesn't look quite right
    * [ ] A320 Cockpit decals look too shiny
    * [ ] Figure out why A320 is importing with livery
    * [ ] Make local texture folder have higher priority/overwrite other files when importing (maybe an option?)
    * [ ] Shader node warning possibly related to normals issues? (04:50:41 | WARNING: More than one shader node tex image used for a texture. The resulting glTF sampler will behave like the first shader node tex image.)
    * [ ] Fix normals issues on some meshes
    * [ ] Fix weird texture issue (https://cdn.discordapp.com/attachments/754092423562395730/800231820398297138/unknown.png)
    * [ ] C172 decal z-fighting
    * [ ] C172 seat metal issues
    * [ ] Better livery checking
    * [ ] `glTFValidator_Added_Default_Material`
    * [ ] FloatVectorProperty max value
* [x] Animations
    * [x] Fix node caching issue that causes duplicate nodes (this makes animations not show up in the sim)
    * [x] Name for animation accessors
    * [x] Seperate input accessors
    * [x] Make animations show up properly in the sim
    * [ ] Some channels are reused, look at Asobo exporter to see how they did it
    * [ ] Auto switching on the overhead default position (https://cdn.discordapp.com/attachments/754092423562395730/800232523892260884/unknown.png)
    * [ ] Kitty glass prebaked reflections (exported doesn't have them, but vanilla does)

* [ ] Miscellaneous
  * [x] Rename back to normal name, not adenflorian
  * [ ] Repo housecleaning
  * [ ] Documentation as well as local documentation - maybe do something with the READMEs in each folder?
  * [ ] Remove .glb references
  * [ ] Maybe tweak naming for plugin in __init__.py
  * [ ] Asobo mesh optimization
  * [ ] Wingflex doesn't work
  * [ ] Liveries on the sharklets don't show up
  * [x] Exporting breaks skeleton animations in Blender
  * [ ] Force absolute path for addon preferences
  * [ ] Some meshes are children of bones? For example WHEEL_HYDROLIC_left has a mesh child
  * [ ] Import/Export settings
  * [x] Custom material properties
  * [ ] Fix 747 import issues (seems to be skinned mesh related) https://discord.com/channels/738864299392630914/754092423562395730/762025731320315934
  * [ ] Possibly more harcoded Asobo buffer views?
  * [ ] Rename animations_bake? Also don't need to check if blender data is an object or a bone because those are the only two possibilities
  * [ ] Undo node duplication fix
  * [ ] Some nodes for some planes import at the wrong location (Caravan's brakes)
  * [ ] Fix issues importing LOD01 breaking the gear wire
  * [ ] Could not load texture warning in sim
  * [ ] Have vertex types affect appearance in Blender
  * [ ] Fix 787 issues
  * [x] Import material issue?
  * [ ] Engine "HOST POINT" decal cutting off
  * [ ] Remove round_if_near?
  * [ ] Get rid of excess prints
  * [ ] Genereate XMLs?
  * [ ] Always export translation, rotation, and scale
  * [ ] NLA track names getting cut off
  * [ ] Not all nodes exporting
  * [ ] Accessors not the same amount
  * [ ] Normals needing to be flipped (for example the back of the engine switching from LOD00 to LOD01)
  * [ ] Replicate file system to make mods work that have custom textures, but not every texture needed
  * [ ] `ASOBO_animation_retargeting` and other extensions from asobo simobjects
  * [x] Fix addon preferences not saving sometimes
  * [ ] Issue with black border on wing
  * [ ] Errors importing some models
  * [ ] Morphing?
  * [ ] Importing lights
  * [ ] Error immediately importing some planes
  * [ ] Jetway importing issues
  * [ ] Weird error in VSCode
  * [ ] Don't export camera and lights
  * [ ] Reindex not working properly
* [ ] Asobo requests
  * [ ] Wingflex documentation (angles applied, bones, etc.)
  * [ ] Armature viewer (since 3DS Max uses dummy helpers)
  * [ ] Material animations?
