### ISSUE TITLE
[TRACKING] Importer/Export Rewrite

### ISSUE THREAD

**Issue by pepperoni505** [flybywiresim/glTF-Blender-IO-MSFS#2]
- [ ] Importer
  - [ ] Model
    - [ ] Figure out proper shading/normals (VEC4 normals)
    - [ ] Fix right spoiler normals
    - [ ] 747 Skinning problems
      - [ ] Possibly related to the fact that the importer doesn't take into account some weights? (like when the A320 had a normalization issue that caused some meshes to be very small)
    - [ ] Some meshes being scaled incorrectly
      - [ ] The sim doesn't support non-uniform scaling
    - [ ] Reimporting a plane has normals issues
      - [ ] Don't import split normals data with optimized meshes
      - [ ] Import non optimized meshes normally 
  - [ ] Animations
  - [ ] Materials
    - [ ] Change normal map z calculation?
    - [ ] Check to make sure community folder is the actual community folder, and not a copy
    - [ ] Rewrite/refactor custom material code
    - [ ] Some materials can have multiple material extensions
    - [ ] Add functionality to all material properties
      - [ ] Texture functionality
        - [ ] Fix node position issues when importing only one texture and then adding others
      - [ ] Property functionality
      - [ ] Material type functionality
    - [ ] Update texconv to use latest reconstructz feature
    - [ ] Not importing alpha for colors? Example: Fuselage_Invisible material on the 747 exterior
    - [ ] Finish Asobo materials
      - [ ] UV Scale for ASOBO_material_detail_map
    - [ ] KeyError: 'bpy_prop_collection[key]: key "Wetness AO" not found'
  - [ ] Miscellaneous
    - [ ] Import options
    - [x] YUP issue with bounding box?
    - [ ] Include Asobo component types in `from_list`?
    - [ ] Buffer view order
    - [ ] 747 Import error
    - [ ] KeyError: -1 when importing
    - [ ] Don't allow morph exports?
    - [ ] Get rid of emission strength
    - [ ] Move some things like the material UI to an extension? There is a good system for that
- [ ] Exporter
  - [ ] Create indices buffer view last?
  - [ ] Force apply modifiers?
  - [ ] Triangulate the mesh if can't calculate tangents
  - [ ] Issues with mirrored meshes
  - [ ] Force some export settings if emulating optimization?
      - [ ] Force tangent calculation if emulating optimization
      - [ ] Force export materials?
      - [ ] Force UVS, vertex colors, and normals 
  - [ ] Fix vertex colors for optimized meshes
  - [ ] Export asobo buffer views in preset order
  - [ ] Handle cases where indices need to be duplicated
